# 1) Model Training

In [7]:
# IMPORTS
from pathlib import Path
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

from mypackage.config import *
from mypackage.utils import *


####
# from sklearn.model_selection import KFold, cross_val_score
# from sklearn.ensemble import RandomForestRegressor
# import numpy as np


## v1: Models without consideration of epigenetics

### v1.0

In [8]:
# LOADING IN DATASET (csv file)
dataset_id = "v1.0.pkl"
v1_0_data = DATA_PROCESSED_EFFICACY / dataset_id
df = pd.read_pickle(v1_0_data)

In [9]:
df

,normalized_efficacy,pos_0_A,pos_0_C,pos_0_G,pos_0_T,pos_1_A,pos_1_C,pos_1_G,pos_1_T,pos_2_A,...,pos_20_G,pos_20_T,pos_21_A,pos_21_C,pos_21_G,pos_21_T,pos_22_A,pos_22_C,pos_22_G,pos_22_T
0,0.164020,0,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
1,0.311196,1,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,1,0
2,0.179397,0,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
3,0.498712,0,1,0,0,0,0,0,1,0,...,0,1,0,0,1,0,0,0,1,0
4,0.233023,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16744,0.287346,0,1,0,0,1,0,0,0,1,...,0,1,0,0,1,0,0,0,1,0
16745,0.209103,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,0,0,1,0
16746,0.061508,0,0,0,1,0,0,1,0,1,...,0,0,0,0,1,0,0,0,1,0
16747,0.181219,1,0,0,0,0,0,0,1,0,...,0,1,0,0,1,0,0,0,1,0
16748,0.045965,0,0,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [10]:

# X = df.drop(columns=["normalized_efficacy"])
# y = df["normalized_efficacy"]

# train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=0)

train_X, _, train_y, _,  = load_data(df)

In [11]:
rf_1_0 = RandomForestRegressor(n_estimators=100, random_state=0)
rf_1_0.dataset_id = dataset_id
rf_1_0.fit(train_X, train_y)

hgb_1_0 = HistGradientBoostingRegressor(random_state=0)
rf_1_0.dataset_id = dataset_id
hgb_1_0.dataset_id = dataset_id
hgb_1_0.fit(train_X, train_y)

xgb_1_0 = XGBRegressor()
xgb_1_0.dataset_id = dataset_id
xgb_1_0.dataset_id = dataset_id
xgb_1_0.fit(train_X, train_y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [12]:
# SMALL EXAMPLE
# data_x = val_X.iloc[0:2]
# preds_x = model1.predict(data_x)
# #print(mean_absolute_error(val_y.iloc[0:2], preds_x))

# print(val_y.iloc[0:2])
# print(preds_x)

In [13]:
# export_model(model1, "rf_v1.0", MODELS_EFFICACY)
# export_model(model2, "hgb_v1.0", MODELS_EFFICACY)

### v1.1

In [14]:
dataset_id = "v1.1.pkl"
v1_1_data = DATA_PROCESSED_EFFICACY / dataset_id
df = pd.read_pickle(v1_1_data)
df

,normalized_efficacy,pos_0_A,pos_0_C,pos_0_G,pos_0_T,pos_1_A,pos_1_C,pos_1_G,pos_1_T,pos_2_A,...,pos_21_T,pos_22_A,pos_22_C,pos_22_G,pos_22_T,pct_A,pct_C,pct_G,pct_T,gc_content
0,0.164020,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0.130435,0.304348,0.434783,0.130435,0.739130
1,0.311196,1,0,0,0,0,1,0,0,1,...,0,0,0,1,0,0.304348,0.304348,0.173913,0.217391,0.478261
2,0.179397,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0.173913,0.217391,0.434783,0.173913,0.652174
3,0.498712,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0.043478,0.347826,0.260870,0.347826,0.608696
4,0.233023,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0.391304,0.130435,0.347826,0.130435,0.478261
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16744,0.287346,0,1,0,0,1,0,0,0,1,...,0,0,0,1,0,0.086957,0.391304,0.391304,0.130435,0.782609
16745,0.209103,0,1,0,0,0,0,0,1,1,...,0,0,0,1,0,0.304348,0.260870,0.130435,0.304348,0.391304
16746,0.061508,0,0,0,1,0,0,1,0,1,...,0,0,0,1,0,0.217391,0.347826,0.260870,0.173913,0.608696
16747,0.181219,1,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0.217391,0.173913,0.347826,0.260870,0.521739
16748,0.045965,0,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0.043478,0.434783,0.217391,0.304348,0.652174

In [15]:
train_X, _, train_y, _,  = load_data(df)

rf_1_1 = RandomForestRegressor(n_estimators=100, random_state=0)
rf_1_1.dataset_id = dataset_id
rf_1_1.fit(train_X, train_y)

hgb_1_1 = HistGradientBoostingRegressor(random_state=0)
hgb_1_1.dataset_id = dataset_id
hgb_1_1.fit(train_X, train_y)

xgb_1_1 = XGBRegressor()
xgb_1_1.dataset_id = dataset_id
xgb_1_1.dataset_id = dataset_id
xgb_1_1.fit(train_X, train_y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [16]:
# kf = KFold(n_splits=2, shuffle=True, random_state=42)
# rf = RandomForestRegressor(n_estimators=500, random_state=42, n_jobs=-1)


# r2_scores = cross_val_score(rf, X, y, cv=kf, scoring='r2')
# print("Mean R2:", np.mean(r2_scores))

In [17]:
# X_train, X_test, y_train, y_test,  = load_data(df)

# rf00 = RandomForestRegressor(n_estimators=100, random_state=0)
# rf00.fit(train_X, train_y)

# evaluate_model(y_test, rf00.predict(X_test))

## v1.2

In [18]:
dataset_id = "v1.2.pkl"
v1_1_data = DATA_PROCESSED_EFFICACY / dataset_id
df = pd.read_pickle(v1_1_data)
df

,normalized_efficacy,pos_0_A,pos_0_C,pos_0_G,pos_0_T,pos_1_A,pos_1_C,pos_1_G,pos_1_T,pos_2_A,...,pos_22_A,pos_22_C,pos_22_G,pos_22_T,pct_A,pct_C,pct_G,pct_T,gc_content,poly_T
0,0.164020,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0.130435,0.304348,0.434783,0.130435,0.739130,0
1,0.311196,1,0,0,0,0,1,0,0,1,...,0,0,1,0,0.304348,0.304348,0.173913,0.217391,0.478261,0
2,0.179397,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0.173913,0.217391,0.434783,0.173913,0.652174,0
3,0.498712,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0.043478,0.347826,0.260870,0.347826,0.608696,0
4,0.233023,1,0,0,0,1,0,0,0,0,...,0,0,1,0,0.391304,0.130435,0.347826,0.130435,0.478261,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16744,0.287346,0,1,0,0,1,0,0,0,1,...,0,0,1,0,0.086957,0.391304,0.391304,0.130435,0.782609,0
16745,0.209103,0,1,0,0,0,0,0,1,1,...,0,0,1,0,0.304348,0.260870,0.130435,0.304348,0.391304,0
16746,0.061508,0,0,0,1,0,0,1,0,1,...,0,0,1,0,0.217391,0.347826,0.260870,0.173913,0.608696,0
16747,0.181219,1,0,0,0,0,0,0,1,0,...,0,0,1,0,0.217391,0.173913,0.347826,0.260870,0.521739,0
16748,0.045965,0,0,0,1,0,1,0,0,0,...,0,0,1,0,0.043478,0.434783,0.217391,0.304348,0.652174,0

In [19]:
train_X, _, train_y, _,  = load_data(df)

rf_1_2 = RandomForestRegressor(n_estimators=100, random_state=0)
rf_1_2.dataset_id = dataset_id
rf_1_2.fit(train_X, train_y)

hgb_1_2 = HistGradientBoostingRegressor(random_state=0)
hgb_1_2.dataset_id = dataset_id
hgb_1_2.fit(train_X, train_y)

xgb_1_2 = XGBRegressor()
xgb_1_2.dataset_id = dataset_id
xgb_1_2.dataset_id = dataset_id
xgb_1_2.fit(train_X, train_y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

## Exporting all models

In [21]:
models = (rf_1_0, rf_1_1, rf_1_2, hgb_1_0, hgb_1_1, hgb_1_2, xgb_1_0, xgb_1_1, xgb_1_2)
filepaths = ("rf_v1.0", "rf_v1.1", "rf_v1.2", "hgb_v1.0", "hgb_v1.1",  "hgb_v1.2", "xgb_v1.0", "xgb_v1.1", "xgb_v1.2")
for model, filepath in zip(models, filepaths):
    export_model(model, filepath, MODELS_EFFICACY)

Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/rf_v1.0.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/rf_v1.1.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/rf_v1.2.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/hgb_v1.0.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/hgb_v1.1.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/hgb_v1.2.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/xgb_v1.0.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/xgb_v1.1.joblib
Model saved to /Users/thewildchip/Desktop/Coding/crispr-genie-lab-jf/models/efficacy/xgb_v1.2.joblib